---
title: Balloon Pi-tay Popper
hero_image: images/banner.png
description: Pop balloons using a different type of pin - a GPIO pin!
original_url: https://raspberrypi.org/learning/balloon-pi-tay-popper
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-1, phys-comp-3, manufacture-1, community-0
interests: humour
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Balloon Pi-tay popper
- title: Wire up a button
- title: Test the button with code
- title: Set up the balloon popper
- title: Connect the transistor
- title: Connect the balloon
- title: Add the balloon to the code
- title: Set up more balloons
  completion: internal
- title: Code more balloons
- title: What next?
